#!/usr/bin/env bash

version="v0.4.1"
SCRIPT_DIR="/opt/javanmap"

for arg in "$@"; do
    if [[ $arg == "--help" || $arg == "-h" ]]; then

        printf "\n\033[1m   ---BEFORE USAGE MAKE SURE JAVA IS INSTALLED!---\033[0m\n"

    echo "
    Javanmap $version ( https://github.com/NerixGO/javanmap )
    Javanmap is a Nmap wroted from scratch with java language!
    Usage: javanmap [option] <target>
    
    TARGET SPECIFICATION:
        Can pass IP addresses
        Ex: 192.168.0.1

    EXAMPLES:
        javanmap 192.168.0.1

    SCAN OPTIONS:
        -p <port>, --port <port>                Use specific port. If port not specified, scan 1000 Most common used ports"

        exit 0

    elif [[ "$1" == "update" ]]; then
        cd "$SCRIPT_DIR"

        echo "Updating..."

        git pull

        ./install.sh

        exit
    fi
done

mkdir -p "$SCRIPT_DIR/bin"

javac -d "$SCRIPT_DIR/bin" "$SCRIPT_DIR"/*.java

echo "Javanmap $version ( https://github.com/NerixGO/javanmap )"

java -cp "$SCRIPT_DIR/bin" Main --data-dir="$SCRIPT_DIR" "$@"